services:
  db:
    image: postgres:16.2-bullseye
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_DB=worktime-db
      - POSTGRES_USER=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
