services:
  db:
    image: postgres:16.2-bullseye
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  worktime:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
        - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
        - DATABASE_URL=${DATABASE_URL}
    container_name: worktime
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - ORIGIN=${ORIGIN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    command: node -r dotenv/config build
    depends_on:
      db:
        condition: service_healthy
        restart: true
