name: Deployment
on:
  push:
    branches: [main]
jobs:
  copy-files-to-server:
    name: Pull Repository on Server
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          separator: ','

      - name: Create .env file
        run: |
          rm -f .env
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}" >> .env
          echo "GH_CLIENT_SECRET='${{ secrets.GH_CLIENT_SECRET }}'" >> .env
          echo "DATABASE_URL='${{ secrets.DATABASE_URL }}'" >> .env
          echo "POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER='${{ secrets.POSTGRES_USER }}'" >> .env

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: ${{ secrets.SSH_LOCAL_PATH }}
